### PR TITLE
centiles-for-measurements

### PR DESCRIPTION
**Pull request by eatyourpeas**
### Overview
Integrates the digital growth charts API to calculate centiles and SDS where heights and weights are provided
Reports these values to the user in the questionnaire

### Code changes
New file `dgc_centile_calculations` which makes the API calls. Note that credentials need to be added to the .env (see settings.py)
`csv_upload` makes the api calls within the async work flow prior to saving the visit
New fields for height/weight/bmi centiles and SDS are added to the Visit model so generate a new migration
These fields are added to the form, but have to set again to None on cleaning otherwise are cast to empty strings which then fails validation
The results are then pulled into the template and have a new template tag to help with this

### Documentation changes (done or required as a result of this PR)
Please describe any changes to documentation here.

### Related Issues
List any issues related to this PR here.

### Mentions
@mentions of the person or team responsible for reviewing proposed changes.

### CODE REVIEW

**Comment by eatyourpeas** [comment]
image

**Comment by mbarton** [comment]
Overdue on [STAGING](https://npda-staging.rcpch.tech) (merged by @eatyourpeas 15 minutes and 5 seconds ago) What's gone wrong?

**Comment by mbarton** [comment]
Seen on [STAGING](https://npda-staging.rcpch.tech) (merged by @eatyourpeas 17 hours, 56 minutes and 43 seconds ago) Please check your changes!

**Comment by mbarton** [comment]
@eatyourpeas I was just reviewing this call for the [External APIs section in the runbook (private link)](https://forum.rcpch.tech/t/npda-audit-platform-runbook/257).

I think centile and SDS are only calculated for CSV uploads. Is this by design? If not I'll raise an issue to add it for the questionnaire too

**Pull request merged**
