### PR TITLE
UI/UX Edits to Home, Navbar and Visit Forms

### PR DESCRIPTION
**Pull request by reecehill**
This pull request includes several changes to the HTML templates for the National Paediatric Diabetes Audit Platform to improve the user interface and experience. The most important changes include mobile-responsive redesigns, adding a smooth scrolling feature, updating the dashboard and home pages, and adding a light-dark mode script (saved to localStorage).

Improvements to HTML templates:

* [`project/npda/templates/base.html`](diffhunk://#diff-d587aed1f46c4563141f432f2d951740f02bc9b0b88cc6c7fe8ee4bc7e6246ddL2-R2): Added a `scroll-smooth` class to the `html` tag for smooth scrolling.
* [`project/npda/templates/base.html`](diffhunk://#diff-d587aed1f46c4563141f432f2d951740f02bc9b0b88cc6c7fe8ee4bc7e6246ddL16-R31): Reformatted the code to improve readability and added a script to save and apply the user's theme preference using `localStorage`. [[1]](diffhunk://#diff-d587aed1f46c4563141f432f2d951740f02bc9b0b88cc6c7fe8ee4bc7e6246ddL16-R31) [[2]](diffhunk://#diff-d587aed1f46c4563141f432f2d951740f02bc9b0b88cc6c7fe8ee4bc7e6246ddR50-R59) **(Toggle hidden by CSS until all pages are compatible with dark/light mode)**

Updates to dashboard and home pages:

* [`project/npda/templates/dashboard.html`](diffhunk://#diff-d72ea2c1864c2cd5d929b6fc77fd54593856a1b4534a17138edd8335298fe224L1-R28): Improved layout and readability by restructuring the HTML.
* [`project/npda/templates/home.html`](diffhunk://#diff-d81b189bd2a110856c6e16cd4aececf0fb37505969cfb9d5b0b20b8252ca133bL6-R23): Enhanced the home page with a new background image, improved layout, and added buttons for better user interaction.

#### Navigation restyle
* responsive, minimise PDU selector, reworded "National" and "Regional" views into apply/remove filters.
image
_Desktop display_

image
_Mobile display_

#### Dashboard update
* Use of DaisyUI hero with insertion of logos
image
_Desktop display_

image
_Mobile display_

#### Patients page update
* Ability to manipulate filters (regional/national views) - Change PDU, Remove filter
* Quick access links added
* Restyle of table
* Table restyled for mobile-first responsive design
* Column filtering uses intuitive swaps for asc/desc sorting by NPDA ID and NHS Number
image
_Desktop display_

image
_Mobile display_

#### Edit visit details update
* Restyled tabs
* Added "Skip to Section" links
* Improved layout (mobile-first responsive design), particularly "Today" and "fill with visit date" buttons
* Added "Click to show/hide section content" to collapses (and enabled >1 to be open at once)

image
_Desktop display_

image
_Desktop display_

image
_Mobile display_

image
_Mobile display_

### CODE REVIEW

**Review by mbarton — COMMENTED** [review]
Thanks @reecehill, this is looking great

Could you please add some screenshots to the PR? It helps a lot for future developers scanning what PR did what change.

We need to be really careful about the effect of changes on Django's (pretty dire) `collectstatic` command. Before this PR it took 10 seconds, it now takes 2 minutes 43. I think this is because it's processing the entire of fontawesome (223MB in the `staticfiles` directory).

Perhaps we remove the icons from this PR and work out how to embed them in a subsequent one? I do want to have icons but at this stage in the project I would prioritise the developer experience speed first.

**Comment by reecehill** [comment]
Appreciate the comments @mbarton 

I'll get the screenshots sorted for you.

I honestly hadn't noticed the `collectstatic` slowdown, my bad. This PR uses FA icons in numerous places; it would be a shame to lose them completely.

The problem with self-hosted FA comes from the different ways it can be implemented: scss, css, webfonts etc. all must be stored.

If developer speed experience is a priority, what're your thoughts on **using CDN to import FontAwesome**? `collectstatic` no longer has to handle the 220MB+ of files this way. I've read a CDN's bundle of FA is only some KB too. 

Otherwise:

- We could embed the SVGs directly (thus no need to import FA). It will bloat .html files and [requires further styling](https://docs.fontawesome.com/web/add-icons/svg-bare), though.
- ....Webpack might help here too

Let me know your thoughts

**Comment by mbarton** [comment]
Makes sense, I think a CDN is the easiest way forward and we already use unpkg for our JS libs

**Comment by eatyourpeas** [comment]
@reecehill are you happy to refactor the fontawesome thing then before I merge in?

**Comment by reecehill** [comment]
> @reecehill are you happy to refactor the fontawesome thing then before I merge in?

@eatyourpeas  All done. Ready for merging.

**Review by mbarton — APPROVED** [review]
Thanks @reecehill, I think this is a great step in the right direction and gives us something we can iterate on to improve the UI even further

:star2:

**Comment by mbarton** [comment]
Seen on [STAGING](https://npda-staging.rcpch.tech) (created by @reecehill and merged by @mbarton 6 minutes and 37 seconds ago) Please check your changes!

**Pull request merged**
