### PR TITLE
Eatyourpeas/issue216

### LINKED ISSUE #216: Normalize PDU
See lucid chart link for details^

# Questions / queries about the current setup

## 1. Normalising PDUs

Image

Highlighted in red, the data regarding `pz_code` is denormalized and multiple models are storing their own versions, sometimes with different fields names. This makes it harder to query. The first proposal here would be to make a single `PDU` table, and reference that via FKs to other tables (*note: using `pdu_id` as the FK, instead of `pz_code` as we technically have a composite key `{pz_code, ods_code}`. makes application logic easier*):

Image

This would make it easier to create KPI queries - there is a single place table where we calculate KPI aggregations

## 2. Purpose of `Site` table

- Is this to enable transfers? @mbarton mentioned depending on the use of the table, we could move its fields into Patient?

## 3. Purpose of `AuditCohort`

Image

It seems the AuditCohort tracks progress for a patient through the audit, linking NPDAUsers to their Patients?

```python
class AuditCohort(models.Model):
    """
    The AuditCohort class.

    This class is used to define the cohort of patients that are being audited. The cohort tracks the progress of the audit
```

I was trying to start the KPI calculations, but I was unsure where to start with KPI1 - eligible patients, defined as:

```
Total   number of patients with:     
... other fields
*  a visit date or admission date within the audit period   
*  Below the age of 25 at the start of the audit period
```

I imagine using `AuditCohort` would determine the audit period but just confused at its relations and purpose. The problem I'm trying to solve is: **for a given pz_code, for a given audit date range, what are the number of eligible patients?**. Thought something like this:

Image

There are also other potentially useful fields:

- `Visit.visit_date`
- `Visit.hospital_admission_date`

# KPI Calculation Implementation

Image

For now, we will run a long single SQL query to return KPI calculations, rather than storing in a model. Building this using the following class which instantiates with a given `pz_code` and `calculation_date` (audit cohort date range calculated using this). It has a `calculate_kpis_for_patients` method, which will calculate and return KPI values for those inputs.

Image

A class-based approach enables us to easily reuse subqueries and attributes throughout the whole calculation (e.g., calculate `audit date range` once at the beginning and use it throughout; the first 12 KPIs are simple counts used as denominators for the subsequent calculations).

We still have localisation of the context of each KPI query logic and can test each independently.

_Originally posted by @anchit-chandran in https://github.com/rcpch/national-paediatric-diabetes-audit/issues/88#issuecomment-2243047170_

### PR DESCRIPTION
**Pull request by eatyourpeas**
Overview
Much discussed first pass refactor of data model
Refactors AuditCohort to Submission model
Adds PaediatricDiabetesUnit model
Sets OrganisationEmployer model as middle table between PDU and NPDAUser
Creates a new Transfer model as a middle table between Patient and PDU
Also a start on the UI workflow within the NPDAUser update form using htmx - allows users to change which

Code changes
reviewing together in person

Documentation changes
This needs addressing

Related Issues
Closes #216

### CODE REVIEW

**Comment by anchit-chandran** [comment]
Tests expected to break as they are based off the old data model.

Will fix in #219

**Review by anchit-chandran — APPROVED** [review]
Went through and discussed on call with @eatyourpeas. 

Expected errors due to updated data model. Next steps to fix:

1) tests
2) csv upload

**Comment by mbarton** [comment]
Overdue on [STAGING](https://npda-staging.rcpch.tech) (created by @eatyourpeas and merged by @anchit-chandran 15 minutes and 5 seconds ago) What's gone wrong?

**Comment by eatyourpeas** [comment]
Merged changes from models refactor into live. This will break tests relating to csv upload as have not touched that. Can fix that later? 
Staging site has a 500 error currently anyway we can fix when you are back. Hope that is ok

**Comment by mbarton** [comment]
Was the 500 error expected? At a minimum we need an issue to track the failure and I wouldn’t advise we do more development until it’s working again.

We should react to Prout noticing about a failure to deploy as if it were the CI GitHub action job failing.

Even though this isn’t deployed to production yet we can’t effectively integrate changes from everyone working on the project if the main pipeline is failing.

**Comment by eatyourpeas** [comment]
Sorry M  - I have looked at this and looks to be an access-token that has expired.
I will raise an issue for it - no one is using this at the moment. I discovered it was down when started to show @AmaniKrayemRCPCH during the sprint. I think it can wait for us to look at together when you are back but if you would prefer I get it back up and running leave it with me and I can fix? LMK :)

**Comment by mbarton** [comment]
The 500 token error probably isn’t related to this merge. The pipeline at the moment will not deploy if the tests fail which they did with an import error:  https://github.com/rcpch/national-paediatric-diabetes-audit/actions/runs/10123171577/job/27996140661.

Let’s get the tests compile fixed and skip anything that needs looking at in separate PRs. That should then get a green deploy. Each deploy gets a fresh access token.

**Comment by eatyourpeas** [comment]
absolutely M. The failing tests all relate to errors in the initial seeding as the models were changed. @anchit-chandran is working on this separately.

**Comment by mbarton** [comment]
Seen on [STAGING](https://npda-staging.rcpch.tech) (created by @eatyourpeas and merged by @anchit-chandran 117 hours, 54 minutes and 34 seconds ago) Please check your changes!

**Pull request merged**
