### PR TITLE
upload-csv-form-validation-fix-implements-single-submission

### PR DESCRIPTION
**Pull request by eatyourpeas**
### Overview
Following the merging of @mbarton branch unifying validation across the project into the form classes, the validation then broke. As well as fixes to this, the PR also removes quarter as a field in the Submission model and the implementations in the patient form where this was previously added in. Quarter has been removed also from all the templates

### Code changes
- `patient_form.py`: removes quarter as a custom field
- `visit_form.py`: adds `clean_**` functions for all the select fields to reject any invalid submitted keys. Accepts None values. TODO: will need to flag errors if for example smoking_status has a valid selection but no associated date.
- `csv_upload.py`: removes quarter as parameter to function which had been previously added and all references to it. Refactors Submission creation to set to inactive previous submission before deletes (#235). Refactors Transfer record creation as did not work following change in table structure.
- `submission.py`: model refactor - removes `quarter`
 - changes to templates largely to remove references to quarter
- `mixins.py`: adds test for related PDU through the Transfer table
- `views/patient.py`: removes references to quarter in filter
- `views/submission.py`: removes references to quarter
- `views/visit.py`: refactors `active_cohort` to submission

### Documentation changes (done or required as a result of this PR)
Possibly needs doing still. Needs likely a section on submission but should do this when clearer how quarters will be handled.

### Related Issues
Addresses #234, #231

### CODE REVIEW

**Comment by mbarton** [comment]
Overdue on [STAGING](https://npda-staging.rcpch.tech) (merged by @eatyourpeas 15 minutes and 3 seconds ago) What's gone wrong?

**Comment by mbarton** [comment]
The container is now crashing on startup in the deployment. Annoyingly there aren't any log messages coming from it either. I'll see if I can start it locally

**Comment by eatyourpeas** [comment]
It I think is because the migrations got reset when the models changed.
Those should not now change

**Comment by mbarton** [comment]
Ah yes sorry there is an error it just took a while to come through in the Azure logs:

```
  Applying npda.0003_alter_submission_options_remove_submission_quarter...
django.db.utils.ProgrammingError: relation "npda_submission" does not exist
```

**Comment by mbarton** [comment]
Seen on [STAGING](https://npda-staging.rcpch.tech) (merged by @eatyourpeas 90 hours, 52 minutes and 8 seconds ago) Please check your changes!

**Pull request merged**
