### PR TITLE
[KPI Calculations] Return pt querysets for each calculations

### PR DESCRIPTION
**Pull request by anchit-chandran**
Signed-off-by: anchit-chandran <anchit97123@gmail.com>

NOTE: RETURNED PT QUERYSETS FOR KPIS 3 ONWARDS ARE NOT TESTED FOR ACCURACY yet (though the retrieval is tightly coupled to the calculation numbers, which ARE tested)

### Overview

Returns the patient querysets for each calculation.

### Code changes

The `CalculateKPIS` has been extended to additionally return pt querysets for each calculation, through the use of the init flag `return_pt_querysets=True` (defaults to `False`).

Example use would be:

```
calculate_kpis_object = CalculateKPIS(return_pt_querysets=True)
```

Then both `calculate_kpis_for_XXX` methods will additionally a `patient_querysets` dict containing 4 keys `eligible`, `ineligible`, `passed`, `failed`, each having values as the relevant `Queryset[Patient]`. E.g.:

```
>>> calculate_kpis_object.calculate_kpis_for_pdus([pz_codes])['calculated_kpi_values']['kpi_10_total_coeliacs']

{
    "kpi_label": "Total number of coeliacs",
    "total_eligible": 6,
    "total_failed": 4,
    "total_ineligible": 4,
    "total_passed": 6,
    "patient_querysets": {
        "eligible": <QuerySet [
            <Patient: ID: 2, 653 765 1948>, 
            <Patient: ID: 6,573 776 5148>, 
            ...
        ]>,
        "ineligible": <QuerySet [
            <Patient: ID: 1,719 573 0220>, 
            <Patient: ID: 3,758 447 7372>, 
            ...
        ]>,
        "passed": <QuerySet [
            <Patient: ID: 2, 653 765 1948>, 
            <Patient: ID: 6, 573 776 5148>, 
            ...
        ]>,
        "failed": <QuerySet [
            <Patient: ID: 2, 653 765 1948>, 
            <Patient: ID: 6,573 776 5148>, 
            ...
        ]>
    },
}
```

NOTE: nuances of each KPI calculation are noted in calculation method docstrings. KPIs 1-12 are counts so 'passed' and 'failed' don't make sense, and returned values should be discarded.

Default behavior (i.e. `return_pt_querysets=False`) of `CalculateKPIS` will return `None` for `patient_querysets`. 

```
>>> CalculateKPIS().calculate_kpis_for_pdus([pz_codes])['calculated_kpi_values']['kpi_10_total_coeliacs']

{
    "kpi_label": "Total number of coeliacs",
    "total_eligible": 6,
    "total_failed": 4,
    "total_ineligible": 4,
    "total_passed": 6,
    "patient_querysets": None
}
```

### Documentation changes (done or required as a result of this PR)

nil 

### Related Issues

#309 

### Mentions
@mentions of the person or team responsible for reviewing proposed changes.

### CODE REVIEW

**Review by eatyourpeas — CHANGES_REQUESTED** [review]
This is great Anchit.
I think something doesn't add up. For example here `total_failed` and `total_ineligible`  both count 10, but the patient_querysets do not match these numbers. I wonder the patient_querysets need to filter against transfer and submission tables too?

```
'calculated_kpi_values': {
     'kpi_10_total_coeliacs': {
         'kpi_label': 'Total number of coeliacs',
         'patient_querysets': {
                'eligible': <QuerySet []>,
                'failed': <QuerySet []>,
                'ineligible': <QuerySet [<Patient: ID: 51, 719 573 0220>, <Patient: ID: 52, 653 765 1948>, <Patient: ID: 53, 758 447 7372>, <Patient: ID: 54, 385 576 6320>, <Patient: ID: 55, 564 764 5542>, <Patient: ID: 56, 573 776 5148>, <Patient: ID: 57, 227 283 6747>, <Patient: ID: 58, 707 712 3626>, <Patient: ID: 59, 999 489 2266>, <Patient: ID: 60, 351 896 1306>]>,
                'passed': <QuerySet []>
        },
        'total_eligible': 0,
        'total_failed': 10,
        'total_ineligible': 10,
        'total_passed': 0
    }
}
```

**Comment by anchit-chandran** [comment]
Some of the KPIs are counts / values so the `pass` / `fail` don't make sense, I think each KPI calculation method should have notes on how to use the values. 

> NOTE: nuances of each KPI calculation are noted in calculation method docstrings. KPIs 1-12 are counts so 'passed' and 'failed' don't make sense, and returned values should be discarded.

KPIs 1-12 are counts so `pass` / `fail` values should just be discarded (I've set them to whatever the first value I could think of, I think for these, `pass=total_eligible` and `fail=total_ineligble`)

The `patient_querysets` returned are identical (for most of the KPIs, I think except for hba1c value ones) to the `total_{eligible|passed|failed|ineligible`; those `total_XXX` numbers come from calling `.count()` on the patient_queryset

**Review by eatyourpeas — COMMENTED** [review]
I see. Might it be clearer if we just set the `pass` and `fail` attributes for 1-12 to None? What do you think?

**Comment by anchit-chandran** [comment]
That would make a lot more sense! Can do for all the ones where it should be ignored

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by eatyourpeas** [comment]
This is the final result with a few changes which include:
- fix for missing labels in 321,322,333
- include 321,322,333 in list between 31 and 33
- add a flag which offers the option to exclude the first 12 measures from results
- redo of the dashboard template to reflect all of the above in the UI

It highlights though a problem with the KPIs generally - which is that none of the measures apply to the individual child. For example, those children with T1DM should be on one of MDI (TDS), MDI (QDS), MDI (QDS) + meds or a pump. These are all measures 14-17. There is no measure that asks whether you are on one of these, only a count of all the people on each.

Unless I have missed something, it is not clear how we signal to users whether a child has passed or failed an individual measure. The way it is currently set up, a child with T1DM on MDI will pass one and fail the rest of 14-17. That does not quite make sense. @AmaniKrayemRCPCH @cillian-rcpch @richardshepherd45 perhaps we could discuss this at next sprint?
image

**Review by eatyourpeas — APPROVED** [review]
Oh yes, and fix the set fails and passes for 1-12 as None and amend the associated tests.
I will approve and merge this but open a new issue for the item described above.

**Comment by mbarton** [comment]
Seen on [STAGING](https://npda-staging.rcpch.tech) (created by @anchit-chandran and merged by @eatyourpeas 6 minutes and 28 seconds ago) Please check your changes!

**Comment by AmaniKrayemRCPCH** [comment]
On the current platform, patient-level KPIs are shown in a big table for that PDU (one row per patient) for some measures. 

image
*no real patient data in the screenshot. This is dummy data.

It's most useful for the care processes (e.g the core health checks, additional care processes, checks at diagnosis). Can also provide the median HbA1c per patient, the number of admissions, albuminuria stage, and requiring additional psych support. 

There may also be further items you would find useful to report on at patient-level. Let's discuss at the sprint call

**Pull request merged**
