### PR TITLE
Use .env file from Azure file share during PR checks

### LINKED ISSUE #392: Use Azure file share .env file during PR checks
Do this:

https://github.com/rcpch/national-paediatric-diabetes-audit/blob/e77f3bc6d4acc8a222d0eec9be5acad40883cffe/s/ci#L6

In this workflow:

https://github.com/rcpch/national-paediatric-diabetes-audit/blob/live/.github/workflows/pytest.yml

At the moment the latter still uses a base64 encoded env file in the repo secrets. For consistency we've decided to keep everything on Azure file shares as that's where the production env files are.

### PR DESCRIPTION
**Pull request by mbarton**
Fixes #392 

Move the PR checks to a script file for consistency with our CI deploy workflow

### CODE REVIEW

**Review by eatyourpeas — APPROVED** [review]
If I am honest I am not sure how to test this exactly. If the tests are passing then that must mean this works as advertised and for sure it all looks good.

**Comment by mbarton** [comment]
Thanks @eatyourpeas. Yes I should have been clearer that I was tagging you and Anchit for visibility rather than a "check it out and test" review.

**Comment by mbarton** [comment]
Seen on [STAGING](https://npda-staging.rcpch.tech) (merged by @mbarton 9 minutes and 54 seconds ago) Please check your changes!

**Comment by mbarton** [comment]
I've deleted the old `ENVIRONMENT` repo secret

**Pull request merged**
